### ISSUE TITLE
Need clarification of text in readme

### ISSUE THREAD

**Issue by michaelnero** [tomlm/Lucene.Net.Store.Azure#6]
I was hoping you could provide a little more context behind the statement

> To be more concrete: you can have 1..N worker roles adding documents to an index, and 1..N searcher webroles searching over the catalog in near real time.

It could just be me being dense, but I'm having a hard time understanding what this means. Could you help explain that?

**Comment by tomlm** [comment]
Sure.  Lucene only allows 1 indexwriter writing to a catalog at a time.  But you can have as many IndexSearchers bound to that catalog as you want, so you can scale our your search load to as many machines as you want.  Every time you create a new IndexSearcher you will be bound to a snapshot of the catalog at that time and then you can serve searches against for as long as you want, until you want to pick up the new version of the catalog.  

For most uses this is sufficient, because write operations much more rare than read (search) operations.  You might do a billion search operations before you have to add new content to your index.

If you are in a situation where you need higher WRITE throughput then a single machine can do, then you can scale out your indexing system by create **multiple catalogs**, each with their own IndexWriter.

You don't have to combine the catalogs together because Lucene allows you to simply combine searchers together, each bound to their underlying catalog.  Esssentially MultiSearcher(IndexSearcher(Catalog1), IndexSearcher(Catalog2), IndexSearcher(Catalog3)) to create a single search view over multiple catalogs Catalog1, Catalog2, Catalog3.

Something like this:
```
IndexMachine1 =>IndexWriter(Catalog1)
IndexMachine2 =>IndexWriter(Catalog1)
...
IndexMachineM =>IndexWriter(CatalogM)

SearchMachine1 => MultiSearcher(IndexSearcher(Catalog1),IndexSearcher(Catalog2),...IndexSearcher(CatalogM))
SearchMachine2 => MultiSearcher(IndexSearcher(Catalog1),IndexSearcher(Catalog2),...IndexSearcher(CatalogM))
.
.
.
SearchMachineN => MultiSearcher(IndexSearcher(Catalog1),IndexSearcher(Catalog2),... IndexSearcher(CatalogM))
```

Effectively you can scale this out to MxN to build a enormous highly performance search engine.
* Scale instances of IndexMachines/Catalogs to be able to index at the rate you need
* Scale instances of SearchMachines to be able to handle the search volume you need.
Make sense?

**Comment by michaelnero** [comment]
Yes, this makes sense now. Thank you very much for taking the time to help!
